require('core.plugins')
require('core.mapping')
require('core.setting')

require('plugins.treesitter')
require('plugins.lsp')
require('plugins.color')
require('plugins.cmp')
require('plugins.lualine')
require('plugins.transparent')
require('plugins.fineline')
require('plugins.neotree')
